on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Start server in the background
        run: |
          npm run build
          npm start &

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: e2e
